# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: test

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set up Database
        run: |
          echo "[DataBase]" > db.ini
          echo "name = ${{ secrets.DB_NAME }}" >> db.ini
          echo "user = root" >> db.ini
          echo "pass = ${{ secrets.DB_PASSWORD }}" >> db.ini
          echo "host = localhost" >> db.ini
          echo "port = 3306"
          

      - name: Start app
        run: flask --app Controller run --host=0.0.0.0 --port=5000 &

      - name: Wait for app to start
        run: sleep 5

      - name: Run tests
        run: python tests/test.py || echo "Failed" >> error.txt
        
      - name: Report Bug on Azure
        if: failure()
        run: |
          az devops configure --defaults organization=https://dev.azure.com/Petrashevich/ project=Test
          az devops login --organization https://dev.azure.com/Petrashevich/ --token ${{ secrets.AZURE_TOKEN }}
          az devops work-item create --type Bug --title "Test Failure" --description "$(cat error.txt)" --output json
